In [1]:
import numpy as np

Create a list

In [2]:
primes = [2, 3, 5, 7, 11, 13, 17]

Append a string to the list.  This won't raise an error.

In [3]:
primes.append('hello')

Until we try to do something like this because the exponent operator doesn't work with strings.

In [4]:
try:
    squares = [x ** 2 for x in primes]
    print(squares)
except TypeError as e:
    print(e)

unsupported operand type(s) for ** or pow(): 'str' and 'int'


So we can filter out everything that is not an integer

In [5]:
squares = [x ** 2 for x in primes if isinstance(x, int)]

But don't forget floats!

In [6]:
squares = [x ** 2 for x in primes if isinstance(x, (int, float))]

In [7]:
squares

[4, 9, 25, 49, 121, 169, 289]

Let's try this with a `numpy` array instead

In [8]:
np_primes = np.array(primes[:-1])

In [9]:
np_primes

array([ 2,  3,  5,  7, 11, 13, 17])

Arrays must be of a homogenous data type

In [10]:
type(np_primes)

numpy.ndarray

In [11]:
np_primes.dtype

dtype('int64')

But they still act a lot like lists

In [12]:
np.append(np_primes, np.array([19, 23]))

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [13]:
_.dtype

dtype('int64')

But what happens if we try to add a float (not an int)

In [14]:
np.append(np_primes, np.array([19, 23, 3.14]))

array([  2.  ,   3.  ,   5.  ,   7.  ,  11.  ,  13.  ,  17.  ,  19.  ,
        23.  ,   3.14])

In [15]:
_.dtype

dtype('float64')

Ok, that makes sense.  Now let's try a string

In [16]:
np.append(np_primes, np.array([19, 23, 3.14, 'foo']))

array(['2', '3', '5', '7', '11', '13', '17', '19', '23', '3.14', 'foo'], 
      dtype='<U32')

In [17]:
_.dtype

dtype('<U32')

This doesn't raise an error either, but instead coerces the types to be alike.

In [18]:
np.append(np_primes, np.array([19, 23, 3.14, 'foo', None, True]))

array([2, 3, 5, 7, 11, 13, 17, 19, 23, 3.14, 'foo', None, True], dtype=object)

In [19]:
_.dtype

dtype('O')

So in the extreme case, numpy gives up and makes everything an object (the root type)

numpy also mirrors the built-in range function

In [20]:
A = np.arange(64, dtype=np.float64)

In [21]:
A

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.])

Arrays have a shape

In [22]:
A.shape

(64,)

This shape can be multi-dimensional

In [23]:
A_prime = A.reshape((4, 2, 8))

In [24]:
A_prime

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.]],

       [[ 16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.],
        [ 24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.]],

       [[ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
        [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.]],

       [[ 48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.],
        [ 56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.]]])

Accessing elements in the array by index is similar to that of the list

In [25]:
A_prime[2]

array([[ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.]])

In [26]:
A_prime[2, 1]

array([ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.])

In [27]:
A_prime[2, 1, 5]

45.0

But we can also choose specific dimensions

In [28]:
A_prime[:, :, 3]

array([[  3.,  11.],
       [ 19.,  27.],
       [ 35.,  43.],
       [ 51.,  59.]])

Works with slicing too!

In [29]:
A_prime[1:3, :, 3:5]

array([[[ 19.,  20.],
        [ 27.,  28.]],

       [[ 35.,  36.],
        [ 43.,  44.]]])

In [30]:
A_prime[2, :, :]

array([[ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.]])

Generate evenly spaced values

In [31]:
np.linspace(0, 10, 11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [32]:
np.arange(0, 11, dtype=np.float64)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [33]:
np.linspace(0, 10, 101)

array([  0. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,   0.8,
         0.9,   1. ,   1.1,   1.2,   1.3,   1.4,   1.5,   1.6,   1.7,
         1.8,   1.9,   2. ,   2.1,   2.2,   2.3,   2.4,   2.5,   2.6,
         2.7,   2.8,   2.9,   3. ,   3.1,   3.2,   3.3,   3.4,   3.5,
         3.6,   3.7,   3.8,   3.9,   4. ,   4.1,   4.2,   4.3,   4.4,
         4.5,   4.6,   4.7,   4.8,   4.9,   5. ,   5.1,   5.2,   5.3,
         5.4,   5.5,   5.6,   5.7,   5.8,   5.9,   6. ,   6.1,   6.2,
         6.3,   6.4,   6.5,   6.6,   6.7,   6.8,   6.9,   7. ,   7.1,
         7.2,   7.3,   7.4,   7.5,   7.6,   7.7,   7.8,   7.9,   8. ,
         8.1,   8.2,   8.3,   8.4,   8.5,   8.6,   8.7,   8.8,   8.9,
         9. ,   9.1,   9.2,   9.3,   9.4,   9.5,   9.6,   9.7,   9.8,
         9.9,  10. ])

In [34]:
np.arange(0, 10.1, .1)

array([  0. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,   0.8,
         0.9,   1. ,   1.1,   1.2,   1.3,   1.4,   1.5,   1.6,   1.7,
         1.8,   1.9,   2. ,   2.1,   2.2,   2.3,   2.4,   2.5,   2.6,
         2.7,   2.8,   2.9,   3. ,   3.1,   3.2,   3.3,   3.4,   3.5,
         3.6,   3.7,   3.8,   3.9,   4. ,   4.1,   4.2,   4.3,   4.4,
         4.5,   4.6,   4.7,   4.8,   4.9,   5. ,   5.1,   5.2,   5.3,
         5.4,   5.5,   5.6,   5.7,   5.8,   5.9,   6. ,   6.1,   6.2,
         6.3,   6.4,   6.5,   6.6,   6.7,   6.8,   6.9,   7. ,   7.1,
         7.2,   7.3,   7.4,   7.5,   7.6,   7.7,   7.8,   7.9,   8. ,
         8.1,   8.2,   8.3,   8.4,   8.5,   8.6,   8.7,   8.8,   8.9,
         9. ,   9.1,   9.2,   9.3,   9.4,   9.5,   9.6,   9.7,   9.8,
         9.9,  10. ])

In [35]:
np.linspace(17, 45.2, 17)

array([ 17.    ,  18.7625,  20.525 ,  22.2875,  24.05  ,  25.8125,
        27.575 ,  29.3375,  31.1   ,  32.8625,  34.625 ,  36.3875,
        38.15  ,  39.9125,  41.675 ,  43.4375,  45.2   ])

In [36]:
np.linspace(0, np.pi*2, 361)

array([ 0.        ,  0.01745329,  0.03490659,  0.05235988,  0.06981317,
        0.08726646,  0.10471976,  0.12217305,  0.13962634,  0.15707963,
        0.17453293,  0.19198622,  0.20943951,  0.2268928 ,  0.2443461 ,
        0.26179939,  0.27925268,  0.29670597,  0.31415927,  0.33161256,
        0.34906585,  0.36651914,  0.38397244,  0.40142573,  0.41887902,
        0.43633231,  0.45378561,  0.4712389 ,  0.48869219,  0.50614548,
        0.52359878,  0.54105207,  0.55850536,  0.57595865,  0.59341195,
        0.61086524,  0.62831853,  0.64577182,  0.66322512,  0.68067841,
        0.6981317 ,  0.71558499,  0.73303829,  0.75049158,  0.76794487,
        0.78539816,  0.80285146,  0.82030475,  0.83775804,  0.85521133,
        0.87266463,  0.89011792,  0.90757121,  0.9250245 ,  0.9424778 ,
        0.95993109,  0.97738438,  0.99483767,  1.01229097,  1.02974426,
        1.04719755,  1.06465084,  1.08210414,  1.09955743,  1.11701072,
        1.13446401,  1.15191731,  1.1693706 ,  1.18682389,  1.20

In [37]:
x = _

In [38]:
y = np.sin(x)

In [39]:
y

array([  0.00000000e+00,   1.74524064e-02,   3.48994967e-02,
         5.23359562e-02,   6.97564737e-02,   8.71557427e-02,
         1.04528463e-01,   1.21869343e-01,   1.39173101e-01,
         1.56434465e-01,   1.73648178e-01,   1.90808995e-01,
         2.07911691e-01,   2.24951054e-01,   2.41921896e-01,
         2.58819045e-01,   2.75637356e-01,   2.92371705e-01,
         3.09016994e-01,   3.25568154e-01,   3.42020143e-01,
         3.58367950e-01,   3.74606593e-01,   3.90731128e-01,
         4.06736643e-01,   4.22618262e-01,   4.38371147e-01,
         4.53990500e-01,   4.69471563e-01,   4.84809620e-01,
         5.00000000e-01,   5.15038075e-01,   5.29919264e-01,
         5.44639035e-01,   5.59192903e-01,   5.73576436e-01,
         5.87785252e-01,   6.01815023e-01,   6.15661475e-01,
         6.29320391e-01,   6.42787610e-01,   6.56059029e-01,
         6.69130606e-01,   6.81998360e-01,   6.94658370e-01,
         7.07106781e-01,   7.19339800e-01,   7.31353702e-01,
         7.43144825e-01,

In [40]:
n = list(range(10))
p = list(range(5, 15))

N = np.array(n)
P = np.array(p)

Adding to lists concatenates them

In [41]:
n + p

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

Adding two arrays does an element wise addition

In [42]:
N + P

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

Or adds a scalar value to each element in the array

In [43]:
N + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
1 / P

array([ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857])

The following three cells do the same thing

In [45]:
squares = []
for x in range(10):
    squares.append(x ** 2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [46]:
list(map(lambda x: x ** 2, range(10)))


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [47]:
[x ** 2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [48]:
np.arange(10) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Filtering

In [49]:
data = np.random.randint(1, 101, size = 25)
data

array([60, 48, 26,  8, 27, 57, 53, 72, 21,  8, 54, 68, 90,  2, 76, 47, 76,
       32, 25, 75, 67, 36,  7,  2, 54])

In [50]:
data < 50

array([False,  True,  True,  True,  True, False, False, False,  True,
        True, False, False, False,  True, False,  True, False,  True,
        True, False, False,  True,  True,  True, False], dtype=bool)

In [51]:
data[data < 50]

array([48, 26,  8, 27, 21,  8,  2, 47, 32, 25, 36,  7,  2])